Dim WSHShell
Set WSHShell = WScript.CreateObject("WScript.Shell")
Reg_Run = WSHShell.RegRead("HKLM\SOFTWARE\AutoRoScript")
WSHShell.Run Reg_Run&"\Winrar\wrar341ru.exe"
WScript.Sleep(5000)
WSHShell.AppActivate("WinRAR")
WScript.Sleep(500)
WshShell.SendKeys("{TAB}")
WScript.Sleep(1000)
WshShell.SendKeys("{TAB}")
WScript.Sleep(1000)
WshShell.SendKeys("{ENTER}")
WScript.Sleep(20000)
WshShell.SendKeys("{ENTER}")
WScript.Sleep(1000)
WshShell.SendKeys("{ENTER}")
WScript.Sleep(1000)
WSHShell.AppActivate("WinRar")
WScript.Sleep(500)
WshShell.SendKeys("%{F4}")
