SELECT COUNT([EXCEPTION_MSG_]) as Failed
FROM [DaletDb].[dbo].[ACT_RU_JOB]
WHERE (EXCEPTION_MSG_ LIKE '%errorCode%' OR EXCEPTION_MSG_ LIKE '%problem%' OR EXCEPTION_MSG_ LIKE '%failed%') AND DUEDATE_ >= DATEADD(DAY, -14, GETDATE())